# Generated by Django 3.1.4 on 2021-01-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processor',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
