# Generated by Django 3.1.4 on 2021-01-07 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_processor_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.IntegerField(default=0)),
                ('profit', models.IntegerField(default=0)),
                ('expense', models.IntegerField(default=0)),
                ('products', models.IntegerField(default=0)),
                ('magnit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.magnit')),
            ],
        ),
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.DeleteModel(
            name='Processor',
        ),
    ]
